# Welcome to Jekyll!
#

# Site settings
title: Aykut Aktaş
description: |
  Software Engineer  
  iOS Developer  
owner: Aykut Aktaş # or company name
first_published: 2021 # if migrating another site, the year of your first publish
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aykut.dev" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/aykutaktas
  github: https://github.com/aykutaktas
  linkedin-square: https://linkedin.com/in/aykutaktas
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
